version: '3.4'

services:
  dockertest:
    depends_on:
      - "cache"
    build:
      context: .
      dockerfile: DockerTest/Dockerfile
    volumes:
      - type: bind
        source: "C:\\Users\\khach\\.aspnet\\https"
        target: /https/
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - "8080:80"
      - "8081:443"
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORTS: 8001
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_Kestrel__Certificates__Default__Password: admin123#1
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/dockertestapp.pfx
  mssql:
    container_name: mssql-db
    hostname: mssql-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'admin123#1'
      MSSQL_DATA_DIR: /var/opt/mssql/data
      MSSQL_PID: 'Developer' 
      MSSQL_TCP_PORT: 1433 
    ports: 
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
  cache:
    container_name: cache
    hostname: cache
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes: 
      - cache:/data
    environment:
      - REDIS_PASSWORD=admin123#1
      - REDIS_PORT=6379
volumes:
  mssql-data:
    driver: local
  cache:
    driver: local